--- 
- hosts: ucds 
  remote_user: vagrant 
  become: yes 
  vars: 
    java_file: jre-8u121-linux-x64.tar.gz 
    ucds_file: URBANCODE_DEPLOY_V6.2.4_TRIAL_MP_.zip 
    install_folder: /opt 
    java_name: "{{install_folder}}/jre1.8.0_121" 
    ucds_install_folder: "{{install_folder}}/ibm-ucd-install" 
    java_archive: "{{install_folder}}/{{java_file}}" 
    ucds_archive: "{{install_folder}}/{{ucds_file}}" 
  
  tasks: 
  - name: install unzip package 
    yum: 
      name: "{{item}}" 
      state: present
    with_items: 
    - unzip 
    - net-tools

  - name: Install java 
    unarchive: 
      src: files/{{java_file}} 
      dest: "{{install_folder}}" 
      creates: "{{java_name}}" 

  - name: set correct java version  
    alternatives: 
      name: java 
      link: /usr/bin/java 
      path: "{{java_name}}/bin/java"  
      priority: 2000 

  - name: Make ucds available for system 
    unarchive: 
      src: files/{{ucds_file}} 
      dest: "{{install_folder}}" 
      creates: "{{ucds_install_folder}}" 
  
  - name: copy install properties for ucds 
    copy:  
      src: files/ucds-install.properties 
      dest: "{{ucds_install_folder}}/install.properties" 

  - name: install ucds 
    environment: 
      JAVA_HOME: "{{java_name}}" 
    shell: "{{ucds_install_folder}}/install-server.sh >> /opt/install.log" 
    args: 
      creates: /opt/ibm-ucd/server/conf 

  - name: create unit File
    copy: 
      src:  files/ucdserver.service
      dest: /etc/systemd/system

  - name: start service
    systemd:
      name: ucdserver.service
      state: started
      enabled: True
      daemon_reload: True
